server:
  port: 8080
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: http://10.0.0.20:31101/gaodawei/config-repo.git
          ignore-local-ssh-settings: true
          strictHostKeyChecking: false
          force-pull: true
          searchPaths: '{application}'
          clone-on-start: true
          username: gaodawei
          password: modicomm