server:
  port: 8080
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alauda-spring-cloud-demo/config-repo.git
          ignore-local-ssh-settings: true
          strictHostKeyChecking: false
          force-pull: true
          searchPaths: '{application}'
          clone-on-start: true
eureka:
  host: eureka-server
  port: 8080
  username: discovery
  password: 3GfhPZQifTpVcu
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${eureka.username}:${eureka.password}@${eureka.host}:${eureka.port}/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
---
spring:
  profile: default
eureka:
  host: 127.0.0.1
  port: 8761