server:
  port: 8080
  undertow:
    max-http-post-size: 0
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程,数量和CPU 内核数目一样即可
    io-threads: 2
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载  io-threads*8
    worker-threads: 16
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 每个区分配的buffer数量 , 所以pool的大小是buffer-size * buffers-per-region
    #   buffers-per-region: 1024 # 这个参数不需要写了
    # 是否分配的直接内存
    direct-buffers: true
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        health.enabled: false
        git:
          uri: git@code.aliyun.com:alauda_cloud/config-repo.git
          searchPaths: '{application}'
          force-pull: true
          clone-on-start: true
          ignore-local-ssh-settings: true
          strict-host-key-checking: false
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEowIBAAKCAQEAuVJFleDbgO+lkYyH88/eim7Wu2diXz3v+BccgCntrX0CNVtQ
            oJM2eg0v9cS40pyWHPHHDiQRTojW/VXrFfKXOJfDC817UqdVayaxjm8H/2J2Emch
            sNrv6HbeZElpXs8jsNplDu+dYcur74eKTnoIfKbe7thm1kzGsB8rmh4s/gxWBHo8
            1xkEfaA0R7cj1VdI7Tkp+MEQ3nvqgUBfE96OL+qXPdwLkZQ8xx9IL6PspD8PmhAM
            wDy0ngZ+NBeTJgt16RKJOjrg89kPqfiZqWLEq3b2vp1+nKtMGU0DEGS5DynnUu/R
            jvOgaDWCTaBby656BO2wrv/+y4znqJxat0ltzQIDAQABAoIBACPbyH0kwjRjqozM
            PW4u1afBpKkkawN0z58Ykbo24reEDc5XOfWoJo1dSd9rTjvqcp1tJxAUaIjir37b
            hh58D0izDNmWy/sFR+Dw3sBpuYlv+tq6u+klo/A+N+/9yHbA6+4HhDBsqu5GY6F4
            f4mJ0WSVQWPD2bozpupjTaOHnTsWwabTXWLzAjnliKiHLNbPnYO/wMDlLW4H8iUK
            qvNt4DLUTX62YpQOwxK+1pSi1tikSF4q6JwD3+ErqD0gYGeqv1po7Ajt53pxhkcW
            Nfx+Dvjcl5WcAkFFCqYDdviFLJm7UqDty5iUj6oLMolatEOQ+95KF9f+R7NLXh3d
            Ggkhm2ECgYEA4Aixa2gjPTahyijYfLBYhxP8Pk0bq/OvvsxBg41hzS3SFigfYRSf
            p+NPYguUwhz6EQmVhMs6pi1tFRAvcwhWnW/4R78F2+zvxXV9r01R1egfLVxFVELt
            JwjcLICy0ENnrGJnp6mC8BbvFyWQ9ntzdx7kv+/l5xxOnT3vOU3JIvkCgYEA08OF
            Yw+gODBeRk5vbnpcFAukJnbQ+QzYuVLoSbAEUl2OVUwqVvugUMleNy9QxC/0hq5K
            TqVRRmYxF7pK5J8/addkx5x6Rn0XBUWcD+oqlPMdoxqvs7OxbZ4dmskvwcZpGCav
            15A0Yhkiy7kk50GMj4+SZUnJ7vRS/rVORUfqgnUCgYBOoX5z7jcAEx6x76gcC2Dm
            +BK+Yx3lOkBivRn5bDP5aa2k7SwmTLDEojmIdfweLUFvnWeHFjVdgfAZRncA7tpH
            o7cGp3sM95ooOdaFIqQoabIXn50Nt/e4jZmJXRplkmLe1CMBa7NzRPlhrGO2vxmF
            o6gx3adZeEv3UHeYKz7/MQKBgH7QtT2oqutbU+nIqQTBNAkxG4GJYAX1goghNUiD
            p2Ln8gf0z9o9YDlhDhIAPN7wVQCeuZM1f2GoazfpcVZOY7xvqEO92qAB41pd4GLL
            eeqvWQ1HOvdj4hpiORpr5zSlLGSxLlbqXeRtZyAXZRk0cQe8FBCiStLV8Cnmy9PD
            iJXNAoGBAL5nV7lT0bIYkPWkBdYPqK92VYY/CrYeBofRtDbikj03wx9PIHMC+9Se
            6TzsuPD2n/VxwritRkbBBdpTR1RuIDsTXUzwR9hWEKy7zf5v61eIjVTWNKjTXBBK
            xq1qSKs+sjOK8UvIrLMY+mkbAvRvlt8vx1Uc2pXj/8GF4lnPi7+l
            -----END RSA PRIVATE KEY-----

eureka:
  host: eureka-server-demo
  port: 8761
  username: discovery
  password: 3GfhPZQifTpVcu
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.username}:${eureka.password}@${eureka.host}:${eureka.port}/eureka